drive/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.homepage, name='homepage'),
    # path("activate/<uidb64>/<token>/",views.activate, name='activate'),
    path('about/',views.about,name='about'),
    path('login/',views.login_request,name='login'),
    path('logout/',views.logout_request,name='logout'),
    path('register/',views.register,name='register'),
    path('user/',views.user_page,name="user_page"),
    path('delete_token/<int:pk>/', views.delete_token, name='delete_token'),
    # path("upload/<source>/",views.upload,name='upload'),
    path("upload/<str:folder>/",views.upload,name='upload'),
    path("delete/",views.delete_files,name="delete_files"),
    path("create_folder/",views.create_folder,name="create_folder"),

    path('folders/<slug:slug>/', views.folder_detail, name='folder_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.utils.text import slugify
import os

class APIToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def get_created_at(self):
        return naturaltime(self.created_at)
    
    def get_expires_at(self):
        return naturaltime(self.expires_at)

class Folder(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
image_formats = [
    ".png",
    ".jpg",
    ".jpeg"
]

class Data(models.Model):
    file = models.FileField()
    folder = models.ForeignKey(Folder,on_delete=models.CASCADE)
    access = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.file.name
    
    def get_created_at(self):
        return naturaltime(self.created_at)
    
    def get_file(self):
        return os.path.basename(self.file.name)
    
    def get_format(self):
        return os.path.splitext(self.file.name)[-1]
    
    def is_image(self):
        if os.path.splitext(self.file.name)[-1] in image_formats:
            return True
        return False

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class  NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True,)

    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username',"email", 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self,commit=True):
        user = super(NewUserForm,self).save(commit=True)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

main/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages 
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.encoding import force_bytes, force_str#force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse
from django.db.models import Case, Value, When, F
from django.db import models

from .forms import NewUserForm
from .token import account_activation_token
from .models import APIToken,Folder,Data

import json
import pytz
import datetime
import os
import jwt

SECRET_KEY_TOKEN = os.environ.get("SECRET_KEY")

def homepage(request):
    # samples = Data.objects.order_by('-created_at')[:3]
    folder = Folder.objects.get(name="/")
    datasets = Data.objects.filter(folder=folder)
    #TODO:
    # Select only folders without "/" in the name
    folders = Folder.objects.all()

    return render(request,
                  template_name='main/homepage.html',
                  context={
                      "folders":folders,
                      "datasets":datasets,
                      "folder":folder,
                      "location":"home",
                      }
                  )


def delete_files(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        selected_items = data.get('selected_items', [])

        for item_id in selected_items:
            try:
                data_item = Data.objects.get(pk=item_id)
                data_item.delete()
            except Data.DoesNotExist:
                pass 

        return JsonResponse({'message': 'Items deleted successfully'})

    return redirect('main:homepage')

def create_folder_view(request):
    if request.method == 'POST':
        folder_name = request.POST.get('folder_name')

        if Folder.objects.filter(name=folder_name).exists():
            messages.error(request, 'A folder with the same name already exists.')
        else:
            # Create the folder
            Folder.objects.create(name=folder_name)
            messages.success(request, f'Folder "{folder_name}" created successfully.')

    return redirect('main:homepage') 

def folder_detail(request, slug):
    folder = get_object_or_404(Folder, slug=slug)
    datasets = Data.objects.filter(folder=folder)
    #TODO:
    # Select folders that starts with the folder name
    # folders = Folder.objects.all()

    return render(request, 'main/homepage.html', {
        # "folders":folders,
        "datasets":datasets,
        "folder":folder,
        "location":slug

        })


def pages(request,folder):
    folder = Folder.objects.get(folder)
    datasets = Data.objects.filter(folder=folder)



# @login_required(login_url='/login/')
def upload(request,folder):#,source):

    if request.method == 'POST':
        
        if folder=="home":
            folder='/'
        folder_object = Folder.objects.get(name=folder)
        files = request.FILES.getlist('file')
        print(request.FILES)
        for file in files:
            print(file)
            dataset = Data(file=file,folder=folder_object)
            dataset.save()
    # if folder=="/":
    #     return redirect('main:homepage')
    # else:
    #     return redirect(f'/folders/{folder}/')
            
    return redirect(request.META['HTTP_REFERER'])

def about(request):

    return render(request,
                  template_name='main/about.html',
                  context={   
                           
                           }
                  )

def logout_request(request):
    logout(request)
    messages.info(request,"You are logged out")
    return redirect("main:homepage")

def login_request(request):
    if request.user.is_authenticated:
        return redirect("main:user")
    else:
        if request.method == "POST":
            form = AuthenticationForm(request,data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username = username,password = password)
                if user is not None:
                    login(request, user)
                    messages.info(request, f"You are logged as {username}")
                    return redirect("main:homepage")
                else:
                    messages.error(request,"Username or password don't match")
            else:
                messages.error(request,"Username or password don't match")
        form = AuthenticationForm()
        return render(request,
                    "main/login.html",
                    {"form":form})

def activate(request, uidb64, token):
    try:
        # uid = force_text(urlsafe_base64_decode(uidb64))
        uid = force_str(urlsafe_base64_decode(uidb64))
        
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.info(request, f"You are logged as {user.username}")
        return redirect("main:homepage")
    else:
        return HttpResponse('Activation link is invalid!')

def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST) 
        if form.is_valid():
            to_email = form.cleaned_data.get('email')
            user_email = User.objects.filter(email=to_email)
            if len(user_email)>0:
                messages.error(request, "The email you are trying to use, is already being used.")
                form = NewUserForm
                return render(request = request,
                              template_name = "main/register.html",
                              context={"form":form})

            # user = form.save()
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            tk = account_activation_token.make_token(user)
            current_site = get_current_site(request)
            mail_subject = 'Activate your DeepForest account.'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':tk,
            })
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            messages.info(request, 'Please confirm your email address to complete the registration')
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
            return render(request = request,
                          template_name = "main/register.html",
                          context={"form":form})
    form = NewUserForm
    return render(request = request,
                  template_name = "main/register.html",
                  context={"form":form})

@login_required
def user_page(request):
    user = request.user
    api_tokens = APIToken.objects.filter(user=user)
    if request.method == 'POST':
        tzname = request.COOKIES.get("django_timezone")
        date = request.POST.get('expires_in_hours')
        if tzname:
            tz = pytz.timezone(tzname)
            date = tz.localize(datetime.datetime.strptime(date, '%Y-%m-%d'))
        else:
            date = datetime.datetime.strptime(date, '%Y-%m-%d')
        
        expires_at = int((date).timestamp())
        
        api_token = jwt.encode({'email': user.email, 'exp': expires_at},  SECRET_KEY_TOKEN, algorithm='HS256')
        APIToken.objects.create(user=user, token=api_token, expires_at=datetime.datetime.fromtimestamp(expires_at, tz))
        return redirect('main:user_page')
    return render(request, 'main/user_page.html', {'user': user, 'api_tokens': api_tokens})

def delete_token(request,pk):
    api_token = APIToken.objects.get(id=pk)
    if api_token.user != request.user:
        messages.error(request, "You don't have permission to delete this token")
        return redirect("user_page")
    api_token.delete()
    messages.success(request, "Token deleted successfully")
    return redirect('main:user_page')

templates/main/about.html
{% extends  "main/header.html"%}

{% block content %}
{% load static %}

<div class="container">
  <p>Drive Félis website</p>
</div> 
{% endblock %}

templates/main/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Felis Drive</title>
  {% load static %}

  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
  />
      <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="icon" href="/static/imgs/cloud-storage.png">
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.6/jstz.min.js"></script>

      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <!-- Optimal Internet Explorer compatibility -->
      <!-- Compiled and minified JavaScript -->
      <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
      <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
      <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
{% include "main/includes/navbar.html" %}

<header>{% include "main/includes/messages.html" %}</header>
  
<main>
  {% block content %}
  {% endblock %}
</main>  
  
  {% include "main/includes/footer.html" %}


<style>
  body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }
  
  main {
    flex: 1 0 auto;
  }
</style>
</body>
</html>

templates/main/homepage.html
{% extends  "main/header.html"%}

{% block content %}
{% load static %}

<div class="container">
  <div class="center">
    <div class="row">
      <div class="col s4">
  
        <form id="deleteForm" method="post" enctype="multipart/form-data" action="{% url 'main:delete_files' %}">
          {% csrf_token %}
          <div class="delete-container">
            <p>Delete selected files</p>
            <label id="deleteButton" class="btn-floating btn-large waves-effect waves-light teal">
                <i class="material-icons">delete</i>
            </label>
          </div>
        </form>
      </div>

  <div class="col s4">
  <form id="uploadForm" method="post" enctype="multipart/form-data" action="{% url 'main:upload' folder=location %}">
    {% csrf_token %}
  
    <div class="upload-container">
      <p>Upload file</p>
      <label for="fileInput" id="uploadButton" class="btn-floating btn-large waves-effect waves-light teal">
          <i class="material-icons">cloud_upload</i>
      </label>
      <input type="file" id="fileInput" name="file" style="display:none" multiple/>
    </div>
  </form>
</div>
  

<div class="col s4">
  <form id="downloadForm" method="post" enctype="multipart/form-data" action="{% url 'main:upload' folder='home' %}">
    {% csrf_token %}
  
    <div class="upload-container">
      <p>Create new folder</p>
      <label for="fileInput" id="uploadButton" class="btn-floating btn-large waves-effect waves-light teal">
          <i class="material-icons">create_new_folder</i>
      </label>
      <input type="file" id="fileInput" name="file" style="display:none" multiple/>
    </div>
  </form>  
  </div> 
</div>
</div>
</div>
</div>


<div class="container" id="dropArea" class="drop-area">
    {% comment %} <div class="section">
      {% for image in images %}
        <a href="{{ image.file.url }}" data-fancybox="gallery" data-caption="{{ image.get_file }}">
          <img src="{{ image.file.url }}" style="max-width: 100px; max-height: 100px;"/>
        </a>
      {% endfor %}    
    </div>  {% endcomment %}
    

    <table id="data-table" class="highlight">
        <thead>
          <tr>
              <th><p>
                <label>
                  <input type="checkbox" />
                  <span></span>
                </label>
              </p></th>
              <th>Name</th>
              <th>Created at</th>
              <th>Download</th>
          </tr>
        </thead>

        <tbody>
            {% for folder in folders %}

              {% if folder.slug %}
              
                <tr data-href="{% url 'main:folder_detail' slug=folder.slug %}"   ondblclick="openLink(this)">
                  <td></td>
                    <td><i class="material-icons icon">folder</i>&nbsp  {{ folder.name }}</td>
                    <td>{{ data.get_created_at }}</td>
                </tr>
              {% endif %}
            {% endfor %}
            {% for data in datasets %}
            
                <tr>
                    <td><p>
                      <label>
                        <input type="checkbox" id={{data.pk}} />
                        <span></span>
                      </label>
                    </p></td>
                    <td>
                      {% if data.is_image %}
                      <a href="{{ data.file.url }}" data-fancybox="gallery" data-caption="{{ data.get_file }}">
                        <img src="{{ data.file.url }}" style="max-width: 30px; max-height: 30px;"/>
                        &nbsp  {{ data.get_file }}</a>
                      {% else %}
                      <i class="material-icons icon">insert_drive_file</i>&nbsp  {{ data.get_file }}
                      {% endif %}
                    </td>
                    
                    <td>{{ data.get_created_at }}</td>
                    <td><a href="{{ data.file.url }}" download="{{data.get_file}}" target="_blank"><i class="material-icons">file_download</i></a>
                  </td>
                </tr>
            {% endfor %}
            
        </tbody>
      </table>

      
</div>

<style>
  .icon {
      vertical-align: middle;
  }
</style>

<script type="text/javascript">
  Fancybox.bind("[data-fancybox]", {

  });
  
  
  document.getElementById('fileInput').addEventListener('change', function() {
    // Automatically submit the form when a file is selected
    document.getElementById('uploadForm').submit();
  });

  function openLink(row) {
    var url = row.getAttribute("data-href");
    window.location.href = url;
  }

  var selectAllCheckbox = document.querySelector('#data-table thead input[type="checkbox"]');
    selectAllCheckbox.addEventListener('change', function() {
        // Get all checkboxes in the table body
        var checkboxes = document.querySelectorAll('#data-table tbody input[type="checkbox"]');

        // Set the state of all other checkboxes based on the "Select All" checkbox
        checkboxes.forEach(function(checkbox) {
            checkbox.checked = selectAllCheckbox.checked;
        });
    });

  document.getElementById('deleteButton').addEventListener('click', function() {
    var selectedItems = getSelectedItems();
    if (selectedItems.length > 0) {
        deleteSelectedItems(selectedItems);
    } else {
        alert('No items selected for deletion.');
    }
});

function getSelectedItems() {
    var selectedItems = [];
    var checkboxes = document.querySelectorAll('#data-table input[type="checkbox"]');
    console.log(checkboxes)

    checkboxes.forEach(function(checkbox) {
        if (checkbox.checked) {
            var itemId = checkbox.id;
            if (itemId.trim() !== '') {
              selectedItems.push(itemId);
          }
        }
    });

    return selectedItems;
}

function deleteSelectedItems(selectedItems) {
    var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    var xhr = new XMLHttpRequest();
    xhr.open('POST', '{% url "main:delete_files" %}', true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('X-CSRFToken', csrfToken); 

    var data = JSON.stringify({ selected_items: selectedItems });

    xhr.onreadystatechange = function() {
        if (xhr.readyState === 4 && xhr.status === 200) {
            console.log('Items deleted successfully');
            location.reload();
        }
    };

    xhr.send(data);
    M.toast({html: 'Files deleted successfully!', classes: 'rounded'});
}

document.getElementById('fileInput').addEventListener('change', function() {
  handleFiles(this.files);
});

function handleDragOver(event) {
  event.preventDefault();
  event.stopPropagation();
  document.getElementById('dropArea').classList.add('drag-over');
}

function handleDragLeave(event) {
  event.preventDefault();
  event.stopPropagation();
  document.getElementById('dropArea').classList.remove('drag-over');
}

function handleDrop(event) {
  event.preventDefault();
  event.stopPropagation();
  document.getElementById('dropArea').classList.remove('drag-over');

  var files = event.dataTransfer.files;
  handleFiles(files);
}

function handleFiles(files) {
  var formData = new FormData();

  for (var i = 0; i < files.length; i++) {
      formData.append('file', files[i]);
      console.log(files[i])
  }
  var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  var xhr = new XMLHttpRequest();
  xhr.open('POST', '{% url "main:upload" folder=location %}', true);
  xhr.setRequestHeader('X-CSRFToken', csrfToken); 
  
  xhr.onreadystatechange = function () {
    if (xhr.readyState === 4) {
        if (xhr.status === 200) {
            M.toast({html: 'Files uploaded successfully!', classes: 'rounded'});
            location.reload();
        } else {
            M.toast({html: 'File upload failed!', classes: 'rounded'});
        }
    }
};
  xhr.send(formData);
}

// Add event listeners to the drop area
var dropArea = document.getElementById('dropArea');
dropArea.addEventListener('dragover', handleDragOver);
dropArea.addEventListener('dragleave', handleDragLeave);
dropArea.addEventListener('drop', handleDrop);

</script>

<style>
  .drop-area {
      border: 2px dashed #ccc;
      padding: 20px;
      text-align: center;
  }

  .drag-over {
      background-color: #f0f8ff; /* Light blue background when dragging over */
  }
</style>

{% endblock %}

templates/main/login.html
{% extends  "main/header.html"%}
{% load static %}

{% block content %}
<div class="section">
    <div class="row">
      <div class="input-field col offset-s4 s4">
    <form method="POST">
        {% csrf_token  %}
        {{form.as_p}}
        <p>
            <button class="btn waves-effect waves-light" type="submit" name="action">Login
               <i class="material-icons right">send</i>
            </button>
        </p>
    </form>

    <p>Forgot your password? <a href="{% url 'password_reset' %}"><strong>Click here</strong></a> to change your password!</p>
    <p>If you don't have an account, please <a href='/register'><strong>register</strong></a> yourself</p>
</div>
</div>
</div> 
{% endblock %}

templates/main/register.html
{% extends  "main/header.html"%}

{% block content %}
<div class="section">
    <div class="row">
        <div class="input-field col offset-s4 s4">
            <form class="col s12" method="POST">
                {% csrf_token  %}
                {{ form.as_p }}
                <p>
                    <button class="btn waves-effect grey darken-3" type="submit" name="action">Register
                        <i class="material-icons right ">send</i>
                    </button>
                </p>
            </form>
            <p>If you already have an account, you may <a href='/login'><strong>log in</strong></a></p>   
        </div>
    </div>
</div> 

<!-- <img src="https://img.icons8.com/ios-filled/50/000000/user.png"/> -->
<!-- <style>
    .errorlist{color:red;
                font-weight:bold;
    }
</style> -->
{% endblock %}

templates/main/user_page.html
{% extends  "main/header.html"%}

{% block content %}

<div class="container">
    <h1>User Information</h1>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>

    <h2>API Tokens</h2>
    {% if api_tokens %}
        <table style="table-layout:fixed;word-wrap: break-word">
            <thead>
                <tr>
                    <th>Token</th>
                    <th>Created At</th>
                    <th>Expires At</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for api_token in api_tokens %}
                    <tr>
                        <td class="truncate">
                            <button id="{{api_token.id}}" onclick="copyToken('{{api_token.token}}')">
                                <i class="material-icons">content_copy</i>
                            </button>
                            {{ api_token.token }}
                        </td>
                        <td>{{ api_token.get_created_at }}</td>
                        <td>{{ api_token.get_expires_at }}</td>
                        <td><a href="{% url 'main:delete_token' api_token.pk %}"><i class="material-icons">delete</i></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You don't have API tokens yet, you can create one in the section below.</p>
    {% endif %}

    <div class="container section">
        <h2>Create API Token</h2>
        <form action="" method="post">
            {% csrf_token %}
            <label for="expires_in_hours">Select the date:</label>
            <input type="text" class="datepicker" id="expires_in_hours" name="expires_in_hours">
            <input type="submit" value="Create">
        </form>
    </div>
</div>

<script>
    options = {'format':"yyyy-mm-dd"}
    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems, options);
  });

  function copyToken(text) {
        navigator.clipboard.writeText(text);
    }

    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone; // e.g. "America/New_York"
    document.cookie = "django_timezone=" + timezone;
</script>



{% endblock %}