drive/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.homepage, name='homepage'),
    # path("activate/<uidb64>/<token>/",views.activate, name='activate'),
    path('about/',views.about,name='about'),
    path('login/',views.login_request,name='login'),
    path('logout/',views.logout_request,name='logout'),
    path('register/',views.register,name='register'),
    path('user/',views.user_page,name="user_page"),
    path('delete_token/<int:pk>/', views.delete_token, name='delete_token'),
    # path("upload/<source>/",views.upload,name='upload'),
    path("upload/<str:folder>/",views.upload,name='upload'),
    path("delete/",views.delete_files,name="delete_files"),
    path("create_folder/",views.create_folder,name="create_folder"),

    path('folders/<slug:slug>/', views.folder_detail, name='folder_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/users/password_reset.html
{% extends "main/header.html" %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends "main/header.html" %}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
    </div>
    <a href="{% url 'main:login' %}">Sign In Here</a>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends "main/header.html" %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/users/password_reset_done.html
{% extends  "main/header.html"%}
{% load static %}

{% block content %}
<div class="alert alert-info">
    An email has been sent with instructions to reset your password
</div>
{% endblock %}